
# =============================================================================
# AUTOSTART
# =============================================================================
exec-once=swaybg -i ~/.config/mango/Wallpaper/violet-wallpaper.png -m fill
exec-once=waybar
exec-once=mako
exec-once=udiskie
exec-once=veilad
