# =============================================================================
# LAYOUTS
# =============================================================================
new_is_master=1
default_mfact=0.55
default_nmaster=1
smartgaps=0

tagrule=id:1,layout_name:scroller
tagrule=id:2,layout_name:scroller
tagrule=id:3,layout_name:scroller
tagrule=id:4,layout_name:scroller
tagrule=id:5,layout_name:scroller
tagrule=id:6,layout_name:scroller
tagrule=id:7,layout_name:scroller
tagrule=id:8,layout_name:scroller
tagrule=id:9,layout_name:scroller

# =============================================================================
# OVERVIEW
# =============================================================================
hotarea_size=10
enable_hotarea=0
ov_tab_mode=0
overviewgappi=5
overviewgappo=30
